数据整理和清理、子集构造和过滤、转换 等快速的矢量化数组运算
常用的数组算法、如排序、唯一化、集合运算

1.创建ndarray

In [2]:
import numpy as np
data1 =[6,7.5,8,0,1]
arr1 = np.array(data1)
print(arr1)

[6.  7.5 8.  0.  1. ]


2.创建嵌套序列

In [3]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


3.转换数据类型

In [7]:
arr = arr2.astype(float)#法一
arr = arr2.astype(arr1.dtype)
print(arr)
print(arr.dtype)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
float64


4.索引和切片

In [20]:
#一维数组
arr = np.arange(10)
print('arr：',arr)
print('arr[5]：',arr[5])
print('arr[1:3]：',arr[1:3])
#二维数组
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('arr2d:',arr2d)
print('arr2d[2]：',arr2d[2])
print('arr2d[0][2]:',arr2d[0][2])#第二层
print('arr2d[0,2]:',arr2d[0,2])#第二层
print('arr2d[[0,2]]:',arr2d[[0,2]])#第一层
print(arr2d[:2,:3])#第二层

arr： [0 1 2 3 4 5 6 7 8 9]
arr[5]： 5
arr[1:3]： [1 2]
arr2d: [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d[2]： [7 8 9]
arr2d[0][2]: 3
arr2d[0,2]: 3
arr2d[[0,2]]: [[1 2 3]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


5.布尔型索引

In [36]:
names = np.array(['bob','joe','will','bob','will','joe','joe'])
data = np.random.randn(7,4)
print('data:',data)
print('names =="bob":',names =='bob')
print('data[(names=="bob")|(names=="will")]:',data[(names=='bob')|(names=='will')])

data: [[ 0.60245091 -1.41835074 -0.10298572 -0.1955835 ]
 [ 0.79769229 -1.39987715  1.56955648 -0.92233477]
 [ 1.13174393  0.66344022 -0.83472816  1.51501509]
 [-0.26552794 -1.39580695 -0.01582561  0.41595324]
 [ 0.32794134  1.23459653 -0.32904375 -1.58237788]
 [-1.29312751  0.03840282 -1.10505036 -0.81868073]
 [ 0.0142504   0.358312   -0.03883173 -1.28022494]]
names =="bob": [ True False False  True False False False]
data[(names=="bob")|(names=="will")]: [[ 0.60245091 -1.41835074 -0.10298572 -0.1955835 ]
 [ 1.13174393  0.66344022 -0.83472816  1.51501509]
 [-0.26552794 -1.39580695 -0.01582561  0.41595324]
 [ 0.32794134  1.23459653 -0.32904375 -1.58237788]]


6.花式索引

In [3]:
arr = np.empty((8,4))
for i in range(8):
    arr[i]=i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


7.数组转置

In [6]:
arr = np.arange(15).reshape((3,5))
print(arr)
arr = np.random.randn(6,3)
np.dot(arr.T,arr)#计算矩阵内积

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 6.6281026 ,  1.74541712, -0.57052106],
       [ 1.74541712,  6.74745057,  4.71662339],
       [-0.57052106,  4.71662339,  7.56718603]])

8.将条件逻辑表述为数组运算

In [ ]:
result=[(x if c else y) for x,y,c in zip(xarr,yarr,cond)]#对大数组的处理速度不是很快，无法用于多维数组
result = np.where(cond,xarr,yarr)

9.数学和统计方法

In [7]:
arr = np.random.randn(5,4)
print(arr)
arr.mean(axis=1)#按行计算
arr.sum(0)#按列计算
arr.cumsum(0)#累加
arr.cumprod()#累乘

[[ 1.79740311  0.54022688  1.14219595  0.05812757]
 [-0.73206899 -1.87554332 -0.50833765  0.63264911]
 [ 0.10105653 -0.04914774  0.57877726 -0.67760983]
 [ 1.19838154  0.78725996  0.86425992  1.91367041]
 [ 1.40735567  0.6781749  -0.61909171  2.10907492]]


10.排序

In [ ]:
arr.sort(1)#返回的是数组已排序的副本

11.读取文本文件

In [ ]:
arr = np.loadtxt('array_ex.txt',delimiter=',')

12.随机数生成

In [8]:
samples = np.random.normal(size=(4,4))

13.矩阵乘法

In [4]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])
y = np.array([[6.,23],[-1,7],[8,9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [10]:
from numpy.linalg import inv,qr
x = np.random.randn(5,5)
mat = x.T.dot(x)
inv(mat)#矩阵的乘法逆矩阵

[[ 3.31903928  1.30508157  0.59537919 -0.53935997  2.26485051]
 [ 1.30508157  4.71039508  0.43258452  0.1271593  -1.1496551 ]
 [ 0.59537919  0.43258452  2.56217035  1.8711921  -0.47989845]
 [-0.53935997  0.1271593   1.8711921   2.48670891 -0.94108885]
 [ 2.26485051 -1.1496551  -0.47989845 -0.94108885  3.42296642]]


14.随机数生成

In [11]:
samples = np.random.normal(size=(4,4))
print(samples)

[[ 0.68630977 -0.77452943 -0.37140549 -0.07576385]
 [-0.97990263 -0.1899546  -1.32189249 -0.93789373]
 [-0.44094375 -0.28086589 -0.07506655 -0.18875003]
 [-0.23197153 -0.37290735  0.35138467 -1.18480087]]


In [20]:
import random
position =0
walk =[position]
steps =1000
for i in range(steps):
    step = 1 if random.randint(0,1) else -1#步长随机加一减一（累计）
    position +=step
    walk.append(position)

In [26]:
nsteps =1000
draws = np.random.randint(0,2,size=nsteps)
steps = np.where(draws>0,1,-1)
walk = steps.cumsum()
walk.min()
walk.max()

77

In [27]:
(np.abs(walk)>=10).argmax()

73